name: server_sync
description: Flutter project to sync and manage a remote server to play minecraft.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bottom_navy_bar: ^5.3.2
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.7.0
  local_auth: ^0.6.1+3
  pedantic: ^1.8.0+1
  provider: ^4.0.4
  shared_preferences: ^0.5.6+3
  simple_animations: ^1.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
